import json
import re
import tkinter as tk
from tkinter import filedialog, ttk
from pathlib import Path

class TMTReplayApp:
    def __init__(self, root):
        self.root = root
        self.root.title("TMT Experiment Playback & Gaze Visualizer")
        self.root.configure(bg="#2b2b2b")

        self.canvas_size = 750
        self.node_radius = int(self.canvas_size * 0.025)

        self.events = []
        self.gaze_samples = []  # Timestamps & (x, y) coordinates from .asc
        self.layout = {}
        self.task_type = "A"
        
        self.current_event_idx = 0
        self.is_playing = False
        self.playback_speed = 1.0

        self._build_ui()

    def _build_ui(self):
        control_frame = ttk.Frame(self.root, padding=10)
        control_frame.pack(fill=tk.X)

        ttk.Button(control_frame, text="Load .JSONL Log", command=self._load_jsonl).pack(side=tk.LEFT, padx=4)
        ttk.Button(control_frame, text="Load .ASC Gaze (Optional)", command=self._load_asc).pack(side=tk.LEFT, padx=4)
        
        self.play_btn = ttk.Button(control_frame, text="Play", command=self._toggle_play, state=tk.DISABLED)
        self.play_btn.pack(side=tk.LEFT, padx=4)
        
        ttk.Button(control_frame, text="Reset", command=self._reset_playback).pack(side=tk.LEFT, padx=4)

        ttk.Label(control_frame, text="Speed:").pack(side=tk.LEFT, padx=(10, 2))
        self.speed_var = tk.StringVar(value="1.0x")
        speed_menu = ttk.Combobox(control_frame, textvariable=self.speed_var, values=["0.5x", "1.0x", "2.0x", "4.0x"], width=5)
        speed_menu.pack(side=tk.LEFT)
        speed_menu.bind("<<ComboboxSelected>>", self._change_speed)

        self.status_lbl = ttk.Label(control_frame, text="Please load a .jsonl session log", foreground="#4da6ff")
        self.status_lbl.pack(side=tk.RIGHT, padx=10)

        # Canvas Area
        self.canvas = tk.Canvas(self.root, width=self.canvas_size, height=self.canvas_size, bg="#f5f5f5", highlightthickness=0)
        self.canvas.pack(pady=10)

    def _load_jsonl(self):
        path = filedialog.askopenfilename(filetypes=[("JSON Lines", "*.jsonl"), ("JSON files", "*.json")])
        if not path:
            return

        self.events = []
        with open(path, "r", encoding="utf-8") as f:
            for line in f:
                if line.strip():
                    self.events.append(json.loads(line))

        if not self.events:
            return

        # Extract initial layout and task type
        first_event = self.events[0]
        self.task_type = first_event.get("task_type", "A")
        targets = first_event.get("targets", [])
        raw_layout = first_event.get("layout", [])
        
        self.layout = {targets[i]: raw_layout[i] for i in range(min(len(targets), len(raw_layout)))}
        
        self.play_btn.config(state=tk.NORMAL)
        self.status_lbl.config(text=f"Loaded: {Path(path).name} ({len(self.events)} events)")
        self._reset_playback()

    def _load_asc(self):
        """Parses an EyeLink .asc file generated by edf2asc."""
        path = filedialog.askopenfilename(filetypes=[("EyeLink ASC files", "*.asc"), ("Text files", "*.txt")])
        if not path:
            return

        self.gaze_samples = []
        # Matches raw gaze lines: <timestamp> <x_coord> <y_coord> <pupil_size>
        sample_pattern = re.compile(r"^(\d+)\s+([\d\.]+)\s+([\d\.]+)\s+([\d\.]+)")

        with open(path, "r", encoding="utf-8", errors="ignore") as f:
            for line in f:
                match = sample_pattern.match(line.strip())
                if match:
                    ts, x, y, _ = match.groups()
                    self.gaze_samples.append((int(ts), float(x), float(y)))

        self.status_lbl.config(text=f"Loaded {len(self.gaze_samples)} gaze points from .asc")

    def _draw_static_layout(self, completed_up_to=0):
        self.canvas.delete("all")
        self.canvas.create_rectangle(0, 0, self.canvas_size, self.canvas_size, fill="#f8f8f8", outline="#eeeeee")

        padding = self.canvas_size * 0.08
        active_area = self.canvas_size - (padding * 2)

        for idx, (target, coords) in enumerate(self.layout.items()):
            x, y = coords
            canvas_x = int((x / 100.0) * active_area + padding)
            canvas_y = int((y / 100.0) * active_area + padding)

            is_completed = idx < completed_up_to
            fill_color = "#90ee90" if is_completed else "#ffffff"
            outline_color = "#2e8b57" if is_completed else "#333333"

            self.canvas.create_oval(
                canvas_x - self.node_radius, canvas_y - self.node_radius,
                canvas_x + self.node_radius, canvas_y + self.node_radius,
                fill=fill_color, outline=outline_color, width=2
            )
            self.canvas.create_text(
                canvas_x, canvas_y, text=target, fill="#111111",
                font=("Segoe UI", int(self.node_radius * 0.7), "bold")
            )

    def _toggle_play(self):
        self.is_playing = not self.is_playing
        self.play_btn.config(text="Pause" if self.is_playing else "Play")
        if self.is_playing:
            self._step_playback()

    def _reset_playback(self):
        self.is_playing = False
        self.current_event_idx = 0
        self.play_btn.config(text="Play")
        self._draw_static_layout(completed_up_to=0)

    def _change_speed(self, event=None):
        speed_str = self.speed_var.get().replace("x", "")
        self.playback_speed = float(speed_str)

    def _step_playback(self):
        if not self.is_playing or self.current_event_idx >= len(self.events):
            self.is_playing = False
            self.play_btn.config(text="Play")
            return

        current_event = self.events[self.current_event_idx]
        event_type = current_event.get("event_type")
        completed_count = current_event.get("completed_count", 0)

        # Redraw nodes based on current trial progress
        self._draw_static_layout(completed_up_to=completed_count)

        # Draw Mouse / Click indicators
        if "x" in current_event and "y" in current_event:
            px, py = current_event["x"], current_event["y"]
            if event_type == "correct_click":
                self.canvas.create_oval(px - 8, py - 8, px + 8, py + 8, fill="#00ff00", outline="#004400")
            elif event_type in ("incorrect_click", "miss_click"):
                self.canvas.create_oval(px - 8, py - 8, px + 8, py + 8, fill="#ff0000", outline="#440000")
            else:
                self.canvas.create_oval(px - 4, py - 4, px + 4, py + 4, fill="#3388ff", outline="")

        # Compute wait time until next recorded event
        delay_ms = 30  # fallback interval
        if self.current_event_idx + 1 < len(self.events):
            next_delta = self.events[self.current_event_idx + 1].get("event_delta_ms")
            if next_delta:
                delay_ms = max(5, int(next_delta / self.playback_speed))

        self.current_event_idx += 1
        self.root.after(delay_ms, self._step_playback)

def main():
    root = tk.Tk()
    app = TMTReplayApp(root)
    root.mainloop()

if __name__ == "__main__":
    main()